name: demo-new-env-copy-print-api-key

on:
  pull_request:
    types: [labeled]

env:
  PROJECT_ID: 538e459351a847058fe28f1e6679b87b #Demo project id (under 'Permit.io Tests' workspace), project Demo
  PR_LABEL: authz

jobs:
  demo-label:
    if: ${{ github.event.label.name == '${{ env.PR_LABEL }}' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get PR number - New env name
      run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

    - name: Creation env pr-${{ env.PR_NUMBER }} under 'Permit.io Tests' workspace, project Demo
      run: |
        response=$(curl -X POST \
          https://api.permit.io/v2/projects/${{ env.PROJECT_ID }}/envs \
          -H 'Authorization: Bearer ${{ secrets.PROJECT_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
          "key": "pr-${{ env.PR_NUMBER }}",
          "name": "pr-${{ env.PR_NUMBER }}"
        }')

        # Extract the new env id
        echo "ENV_ID=$(echo "$response" | jq -r '.id')" >> $GITHUB_ENV

        echo "New env ID: ${{ env.ENV_ID }}"

    - name: Fetch API_KEY of ${{ env.ENV_ID }}
      run: |
        response=$(curl -X GET \
          https://api.permit.io/v2/api-key/${{ env.PROJECT_ID }}/${{ env.${{ env.ENV_ID }} }} \
          -H 'Authorization: Bearer ${{ secrets.PROJECT_API_KEY }}')

        # Extract the secret from the response which is the API_KEY of the new env
        echo "ENV_API_KEY=$(echo "$response" | jq -r '.secret')" >> $GITHUB_ENV

        echo "New env api key: $ENV_API_KEY"
    
    - name: Fetch Development env id
      run: |
        response=$(curl -s -X GET https://api.permit.io/v2/projects/{{ env.PROJECT_ID }}/envs \
          -H 'Authorization: Bearer ${{ secrets.PROJECT_API_KEY }}' \
          -H 'Content-Type: application/json')

        # Extract and echo the ID of the "dev" environment
        echo "DEV_ID=$("$response" | jq -r '.[] | select(.key == "dev") | .id')" >> $GITHUB_ENV

        echo "Development env ID is: $DEV_ID"


    - name: Copy from 'Development' to 'pr-${{ env.PR_NUMBER }}'
      run: |
        curl -X POST https://api.permit.io/v2/projects/${{ env.PROJECT_ID }}/envs/${{ env.DEV_ID }}/copy \
          -H 'Authorization: Bearer {{ secrets.PROJECT_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
            "target_env": {
                "existing": "${{ env.ENV_ID }}"
            }
        }'

    - name: Comment PR with api_key of new env
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.TOKEN_GITHUB }}
        script: |
          if ('${{ github.event_name }}' != 'pull_request') {
            console.log('Not a PR, skipping');
            return;
          }
          const { data } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const comment = `API Key of the new environment pr-${{ env.PR_NUMBER }}: ${{ env.ENV_API_KEY }}`;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: comment
          });
          console.log(`Commented on PR with: ${comment}`);
  